name = "Bobby"
uuid = "bd34264e-e812-11e8-1ee8-bfb20fea2fb4"
authors = ["Alessandro Melis <alessandro_melis@rocketmail.com>"]
version = "1.0.2"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Crayons = "4.0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
